"""Small repository/unit-of-work contract used by services and Agent tools."""

from __future__ import annotations

from typing import Any, Protocol


class DataSession(Protocol):
    """Common surface implemented by SQLAlchemy Session and CloudBase HTTP."""

    is_cloudbase_http: bool

    def get(self, model: type[Any], primary_key: Any) -> Any | None: ...
    def scalars(self, statement: Any) -> Any: ...
    def scalar(self, statement: Any) -> Any: ...
    def add(self, instance: Any) -> None: ...
    def add_all(self, instances: list[Any]) -> None: ...
    def delete(self, instance: Any) -> None: ...
    def execute(self, statement: Any) -> Any: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def refresh(self, instance: Any) -> None: ...
    def expire_all(self) -> None: ...


class RpcDataSession(DataSession, Protocol):
    def rpc(self, function_name: str, parameters: dict[str, Any]) -> Any: ...
